version: '3'

volumes:
  pg_data: {}

services:
  app:
    build: .
    container_name: 'service_order'
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - '8000:80'
    env_file:
      - .env
    environment:
      FLASK_APP: autoapp.py
    stdin_open: true
    tty: true
    command: 
      - web-local
  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"  
    restart: always
    environment:
      POSTGRES_DB: so
      POSTGRES_USER: so_user
      POSTGRES_PASSWORD: so_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"
    hostname: redis
    logging:
      driver: none
